from requests import put, get
import json


class SendJSON:

    @staticmethod
    def sending(temp):
        temp = int(temp)  # bridge requires int type

        address = 'http://192.168.1.12/api/YqRUanSsJWqimwEXaox6OaxaRS8UxIoMjuv5IvNg/lights/3/state/'
        # address is  http://bridge_address/api/autogenerated_user_key/lights/state

        obj = {u"sat": temp}
        payload = json.dumps(obj)

        put(address, payload)